### ISSUE TITLE
Can this work be used without IMU?

### ISSUE THREAD

**Issue by xiaobrnbrn** [TixiaoShan/LVI-SAM#1]
Hello, I would like to know whether this work can be used for the fusion of only camera and lidar or worked with a 6-axis IMU?

**Comment by TixiaoShan** [comment]
An IMU is a must. The camera module can work with a 6-axis IMU. The lidar module currently needs a 9-axis IMU, but it can support a 6-axis with some code changes.

**Comment by xiaobrnbrn** [comment]
> An IMU is a must. The camera module can work with a 6-axis IMU. The lidar module currently needs a 9-axis IMU, but it can support a 6-axis with some code changes.

Thanks, I got it!

**Comment by GuoFeng-X** [comment]
> > An IMU is a must. The camera module can work with a 6-axis IMU. The lidar module currently needs a 9-axis IMU, but it can support a 6-axis with some code changes.
> 
> Thanks, I got it!

hello, please How to modify the code to support 6-axis IMU?

**Comment by zuowei1998** [comment]
Hello, do you know how to modify he code to support 6-axis IMU? Thanks!
