### ISSUE TITLE
If I am not using a fisgeye camera

### ISSUE THREAD

**Issue by ferrari700** [TixiaoShan/LVI-SAM#11]
Hello, if I am not using a fisheye camera, but a logitech c930e, which code parameters should I modify，thank you very much!

**Comment by engcang** [comment]
Refer my [repo](https://github.com/engcang/SLAM-application/blob/main/lvi-sam/params_camera.yaml) and result [video](https://youtu.be/RCY_q_d2Xm0), but I got quite unstable result.

**Comment by ferrari700** [comment]
> 请参阅我的[回购](https://github.com/engcang/SLAM-application/blob/main/lvi-sam/params_camera.yaml)和结果[视频](https://youtu.be/RCY_q_d2Xm0)，但结果非常不稳定。

Thank you, I also have the same problem as your movie, I encountered imu drift problem when turning.I use velodyne-16 and Microstrain 3DM-GX5-25
