### ISSUE TITLE
question about  "q_lidar_to_cam q_lidar_to_cam_eigen"

### ISSUE THREAD

**Issue by HeXu1** [TixiaoShan/LVI-SAM#19]
Hi,thanks for your great works. 
the code test well with your data,but it seems the vins program did not work well with my data. I’m confused about what the “question about  q_lidar_to_cam q_lidar_to_cam_eigen” mean in the code. hope your reply ,thanks agian.
@TixiaoShan

**Comment by HeXu1** [comment]
![Screenshot from 2021-06-07 15-59-37](https://user-images.githubusercontent.com/31620307/120980643-669e8f80-c7a9-11eb-8d83-22868657a9d6.png)
![Screenshot from 2021-06-07 15-58-28](https://user-images.githubusercontent.com/31620307/120980697-7322e800-c7a9-11eb-8b0f-1bfe82476f46.png)

**Comment by HeXu1** [comment]
my imu align lidar well,the first show lvi-sam works with vins but vins failed,the second show lvi-sam works with lio-sam only it works well.

**Comment by epicjung** [comment]
> Hi,thanks for your great works.
> the code test well with your data,but it seems the vins program did not work well with my data. I’m confused about what the “question about q_lidar_to_cam q_lidar_to_cam_eigen” mean in the code. hope your reply ,thanks agian.
> @TixiaoShan

Check this repository (https://github.com/epicjung/LVI_SAM_fixed). I have changed the code for it to work for general cases. Please let me know if the modified version does not work for you.

**Comment by HeXu1** [comment]
@epicjung thanks a lot. I will test it a few days later.
