### ISSUE TITLE
使用handheld数据测试效果发生多次跳变

### ISSUE THREAD

**Issue by dzy130120** [TixiaoShan/LVI-SAM#2]
使用handheld.bag实验效果发现偶尔会出现跳变，不知是否针对这个数据集程序中的参数还需要调整哪些？

**Comment by slam-art** [comment]
I found a solution, you can try to reduce the playback speed of the bag file, refer to this [blog](https://blog.csdn.net/learning_tortosie/article/details/116051761?spm=1001.2014.3001.5501) for details.

**Comment by slam-art** [comment]
> 使用handheld.bag实验效果发现偶尔会出现跳变，不知是否针对这个数据集程序中的参数还需要调整哪些？

I found a solution, you can try to reduce the playback speed of the bag file, refer to this [blog](https://blog.csdn.net/learning_tortosie/article/details/116051761?spm=1001.2014.3001.5501) for details.

**Comment by dzy130120** [comment]
> > 使用handheld.bag实验效果发现偶尔会出现跳变，不知是否针对这个数据集程序中的参数还需要调整哪些？
> 
> I found a solution, you can try to reduce the playback speed of the bag file, refer to this [blog](https://blog.csdn.net/learning_tortosie/article/details/116051761?spm=1001.2014.3001.5501) for details.

非常感谢，确实降低数据速度可以正常运行，效果不错，可能是由于我计算机cpu的问题不能按照数据包实际的时间运行
