### ISSUE TITLE
This system cannnot save pose like Vins-Mono?

### ISSUE THREAD

**Issue by AFS-Suematsu** [TixiaoShan/LVI-SAM#23]
Vins-Mono can save pose graph and reuse pose graph for relocalization.
Can LVI-SAM save pose graph?

**Comment by gisbi-kim** [comment]
@AFS-Suematsu 
I think you may be interested in the pose saver within [SC-LIO-SAM](https://github.com/gisbi-kim/SC-LIO-SAM) and the relocalization of [LT-mapper](https://github.com/gisbi-kim/lt-mapper) that takes the pose graph saved from the SC-LIO-SAM.

**Comment by hellopopyee** [comment]
I wrote a code to solve this problem, just imitate the output code of vins, and contact me if necessary.

**Comment by AFS-Suematsu** [comment]
Thank you
I'm going to try using SC-LIO-SAM.
