### ISSUE TITLE
large velocity or bias, reset IMU-preintegration!

### ISSUE THREAD

**Issue by SnowCarter** [TixiaoShan/LVI-SAM#29]
There will be a significant drop in the z-axis after around 2mins running. After then, LVI-SAM will become totally unstable. 
Is there anybody who comes across this issue?
![Screenshot from 2021-10-13 18-54-30](https://user-images.githubusercontent.com/33834347/137224132-5cc82906-66c8-4252-a329-c3ad83d33de3.png)
![Screenshot from 2021-10-11 20-16-23](https://user-images.githubusercontent.com/33834347/137224178-ce69fa3a-27d6-40db-b434-7d4127bb1277.png)
![Screenshot from 2021-10-13 18-55-05](https://user-images.githubusercontent.com/33834347/137224249-1eedbeea-7245-4ed6-8ae1-195cab569a34.png)

**Comment by SnowCarter** [comment]
Sorry guys, not the problem of LVI-SAM. It was caused by RVIZ because RVIZ took up too much computing resources.

**Comment by zilong-ding** [comment]
我是在楼道内测试，也遇到了这个问题，我是给予了IMU更多信任

**Comment by Lyk77** [comment]
@zilong-ding How to do it？I also encountered this problem。

**Comment by SnowCarter** [comment]
For me, I just turn off some display options in RVIZ: like turning off all of pointcloud2 msg. However, it can also be because of the IMU noise as the @zilong-ding mentioned. You can redo the IMU calibration and maybe increase the noise value by times 10.

**Comment by jeychandar** [comment]
> Sorry guys, not the problem of LVI-SAM. It was caused by RVIZ because RVIZ took up too much computing resources.

Can I know where this error came from. I tried alot but could not find. Having the same issue but I am working with li_slam_ros2 repo. Could you help me out. Thanks in advance.

![image](https://user-images.githubusercontent.com/48254471/209656614-528ccf71-81c9-4c04-b20f-cf8f1864a7b9.png)
