### ISSUE TITLE
How did you get the params lidar_to_cam?

### ISSUE THREAD

**Issue by hitbg-yjm** [TixiaoShan/LVI-SAM#3]
params_camera.yaml:
lidar_to_cam_tx: 0.05
lidar_to_cam_ty: -0.07
lidar_to_cam_tz: -0.07
lidar_to_cam_rx: 0.0
lidar_to_cam_ry: 0.0
lidar_to_cam_rz: -0.04

The lidar's coordinate system(z) is up, and the camera's coordinate system(z) is forward.
But in the yaml, rpy is 0 0 -0.04,
It's almost the same coordinate system.

**Comment by Woodpecker0** [comment]
@hitbg-yjm I have the same question, have you figure it out?

**Comment by hitbg-yjm** [comment]
> @hitbg-yjm I have the same question, have you figure it out?


I don't think it's right, because the parameters are used in the point cloud conversion. Maybe the camera coordinate system is different.

**Comment by Woodpecker0** [comment]
> > @hitbg-yjm I have the same question, have you figure it out?
> 
> I don't think it's right, because the parameters are used in the point cloud conversion. Maybe the camera coordinate system is different.

yes, I read the code, and it seems that this transformation is only used as an offset (transform point to the center of imu)
