### ISSUE TITLE
Experiment on NTU VIRAL datasets

### ISSUE THREAD

**Issue by brytsknguyen** [TixiaoShan/LVI-SAM#31]
Hi Tixiao,

I am trying to do some experiments of LVI SAM on the NTU VIRAL public dataset (download page: https://ntu-aris.github.io/ntu_viral_dataset/). Hence, I will include LVI-SAM to the list of applicable methods to NTU VIRAL website.

However LVI SAM diverges quickly after a few minutes. This does not happen if the visual nodes are disabled. Could you please take a look at the configurations and suggest the best configurations?

The forked repository can be found here:
https://github.com/brytsknguyen/LVI-SAM

Working examples of LIO SAM and VINs-Mono on NTU VIRAL datasets can be found here:
https://github.com/brytsknguyen/LIO-SAM
https://github.com/brytsknguyen/VINS-Mono

**Comment by narutojxl** [comment]
Hi @brytsknguyen, when i playing lvi-sam dataset, i also met this problem. Maybe you can try with a slower playback rate  `play dataset.bag -r 0.5`, because my computer is not powerful.

**Comment by brytsknguyen** [comment]
> Hi @brytsknguyen, when i playing lvi-sam dataset, i also met this problem. Maybe you can try with a slower playback rate `play dataset.bag -r 0.5`, because my computer is not powerful.

Hi @narutojxl,

Thanks for the tip. I have added the transform from lidar to camera and the divergence no longer occurs. You can take a look at my configuration at the forked repo. Do try out NTU VIRAL with your works :)

**Comment by h-k8888** [comment]
@brytsknguyen 
Hi，I'm also trying to do some experiments of LVI-SAM with pinhole camera. Is the launch and yaml files in https://github.com/brytsknguyen/LVI-SAM work for  NTU VIRAL public dataset?

**Comment by WenZheDing** [comment]
> > Hi @brytsknguyen, when i playing lvi-sam dataset, i also met this problem. Maybe you can try with a slower playback rate `play dataset.bag -r 0.5`, because my computer is not powerful.
> 
> Hi @narutojxl,
> 
> Thanks for the tip. I have added the transform from lidar to camera and the divergence no longer occurs. You can take a look at my configuration at the forked repo. Do try out NTU VIRAL with your works :)

Hi @brytsknguyen ，i want to know whether you have compared the result of LVI-SAM and LIO-SAM on ntu viral dataset; for me, when i test it on sups dataset (a parking lot dataset) and evaluate it with evo, LVI-SAM produced worse result than LIO-SAM, and i haven't found the reason yet
