### ISSUE TITLE
lvi_sam_mapOptmization terminated

### ISSUE THREAD

**Issue by neil45853584** [TixiaoShan/LVI-SAM#33]
Hello, the LVI_SAM runs normally in the first few times, but I have encountered the following problems in recent times.

How can I solve it?

#############################################################################################
*** stack smashing detected ***: /home/.../catkin_ws/devel/lib/lvi_sam/lvi_sam_mapOptmization terminated
[lvi_sam_mapOptmization-6] process has died [pid 23959, exit code -6, cmd /home/.../catkin_ws/devel/lib/lvi_sam/lvi_sam_mapOptmization __name:=lvi_sam_mapOptmization __log:=/home/.../.ros/log/7e9a70bc-4752-11ec-87cb-5405dbb6548a/lvi_sam_mapOptmization-6.log].
log file: /home/.../.ros/log/7e9a70bc-4752-11ec-87cb-5405dbb6548a/lvi_sam_mapOptmization-6*.log
[lvi_sam_mapOptmization-6] restarting process
process[lvi_sam_mapOptmization-6]: started with pid [24765]
##############################################################################################

**Comment by grandoba** [comment]
I had the same problem and fixed it by following the instructions given by this author on the README.md page when building GTSAM.
Having the following cmake arguments solved the problem. 
```sh
cmake -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF ..
```
