### ISSUE TITLE
可以使用自己的robosense、MicroStrain 3DM-GX3-25与罗技单目相机吗？

### ISSUE THREAD

**Issue by jinzhenmu** [TixiaoShan/LVI-SAM#36]
各位大佬，有人试过，使用自己的传感器跑LVI-SAM没？能否交流一下

**Comment by GarronLiu** [comment]
Could you write an E-mail to me ljr799910832@sjtu.edu.cn? May be we can have a discussion.

**Comment by skyrim835** [comment]
I can run with my devices,you can look up to https://github.com/skyrim835/LVI-SAM-modified

**Comment by HandsomeJunJun** [comment]
大佬，3DM-GX4-25你是否使用GPS的PPS进行时间同步了。。。

**Comment by jinzhenmu** [comment]
> 同步了。。。

我还没测试。。。。正在准备中

**Comment by HandsomeJunJun** [comment]
能加您微信嘛，我使用GPS的GPRMC和PPS对3DM-GX4-25进行了同步，但有点问题，想与您交流以下。。。我的微信号是jun1067401059或者1067401059。
