### ISSUE TITLE
Test bag(more than 10G) couldn't be downloaded from the google drive

### ISSUE THREAD

**Issue by wwtinwhu** [TixiaoShan/LVI-SAM#4]
Hello @TixiaoShan,
Thanks for your great work! I couldn't download the test data from the google drive due to it's size is larger than 10G. Could you consider to upload your data to Baidu Netdisk? This may be convenient to people in China.

**Comment by 14212094** [comment]
@wwtinwhu You should download these three bag together.(三个一起下或者两个一起下，单个下好像就是不行)

**Comment by wwtinwhu** [comment]
> @wwtinwhu You should download these three bag together.(三个一起下或者两个一起下，单个下好像就是不行)

谢谢，两个下就可以了。请问你下载下来了吗？方便传到百度网盘吗？我这里下的很慢。

**Comment by 14212094** [comment]
@wwtinwhu 我下下来了，但是百度网盘没开会员。。。只能传4G以下的文件

**Comment by wwtinwhu** [comment]
> @wwtinwhu 我下下来了，但是百度网盘没开会员。。。只能传4G以下的文件

好的
