### ISSUE TITLE
Lidar camera calibration

### ISSUE THREAD

**Issue by THARUN-V** [TixiaoShan/LVI-SAM#43]
Hi, 
How did u get the extrinsics of lidar and camera 
Any ideas??

**Comment by skyrim835** [comment]
rx ry rz are close to 0,may be they're not the true extrinsics.

**Comment by wjf1997** [comment]
> 

请问外参是0的原因是作者搭建硬件的时候故意设置的吗？我看到你的modified版本将外参改了过来

**Comment by wjf1997** [comment]
> rx ry rz are close to 0,may be they're not the true extrinsics.

请问外参是0的原因是作者搭建硬件的时候故意设置的吗？我看到你的modified版本将外参改了过来

**Comment by wjf1997** [comment]
> rx ry rz are close to 0,may be they're not the true extrinsics.

但是我从原代码计算相机和IMU的外参，以及lidar和IMU的外参，得到的相机到雷达的外参不是0，还是说这是作者写代码的技巧吗
