### ISSUE TITLE
<------- Reprojection of trajectory on Google Maps ------------->

### ISSUE THREAD

**Issue by THARUN-V** [TixiaoShan/LVI-SAM#45]
Hi guys,
How did u plot the trajectory on google maps...

**Comment by JokerJohn** [comment]
> Hi guys, How did u plot the trajectory on google maps...

maybe you can reference to this repo [LIO_SAM_6AXIS](https://github.com/JokerJohn/LIO_SAM_6AXIS), just transform all of your optimized poses in GPS coordinate and save them as KML file.
![image](https://user-images.githubusercontent.com/25702851/178714466-5b2f607d-b2cc-420e-afb5-ac24db0e875a.png)
