### ISSUE TITLE
Which is the local position output topic?

### ISSUE THREAD

**Issue by Cristian-wp** [TixiaoShan/LVI-SAM#49]
Sorry for the dummy question, but I can not understan which is the position topic.
I have understand that **/lvi_sam/lidar/mapping/odometry** is related to the fusion LIDAR+IMU (LIO-SAM output) and **/lvi_sam/vins/odometry/odometry** is related to CAMERA+IMU (VINS-MONO output).
But which is the one that gives the fusion of both algorithms?

**Comment by wpwebrobotics** [comment]
Based on code and this discussion: https://github.com/TixiaoShan/LVI-SAM/issues/7,
I think the topic to look at is /lidar/mapping/odometry published by mapOptmization.cpp as VIO is used only for the initial guess of LIO sub-system.
Can anyone confirm this?

**Comment by Wangben1019** [comment]
Have you obtained the answer to this question？Is the final topic /lvi_sam/lidar/mapping/odometry ?
