### ISSUE TITLE
Question about Lidar-Inertial System Fail detection

### ISSUE THREAD

**Issue by Taeyoung96** [TixiaoShan/LVI-SAM#53]
@TixiaoShan   
Thanks for your great work!  
In the [LVI-SAM paper](https://arxiv.org/pdf/2104.10831.pdf), this algorithm adapted LIS(LiDAR inertial system) fail detection.  

<p align="center"><img src="https://user-images.githubusercontent.com/41863759/178198225-2f6e782d-0aba-4b7b-87ce-c9eb01ebadcb.png" width = "500" ></p>  

However, maybe because I'm an newbie, I couldn't find which part of the code it was.  
Which part of the code has the LIS fail detection part implemented?  

Thanks,

**Comment by Cristian-wp** [comment]
I need this information too...sometimes at start the two part of the slam can not work well and the pose start to spin, jump,ecc...this occut in the same bag with same parameters in both yaml.
