### ISSUE TITLE
calibration of fisheye and Lidar

### ISSUE THREAD

**Issue by kakghiroshi** [TixiaoShan/LVI-SAM#54]
Hi!
    Thanks for your excellent work. I am running your algorithm, but I do not know how to calibrate fisheye and Lidar.
could you please tell me how do you calibrate and which algorithm you use to finish calibration?
   
Many thanks! :)

**Comment by Cristian-wp** [comment]
I had use this and its working: https://github.com/heethesh/lidar_camera_calibration

**Comment by gara-9527** [comment]
@Cristian-wp Thanks for your kindly sharing！
One thing must be mentioned is that our fisheye's FOV is 180 degree. I wonder if this method would still work with such a large FOV？
Thanks again!
