### ISSUE TITLE
difference between code and article

### ISSUE THREAD

**Issue by wjf1997** [TixiaoShan/LVI-SAM#57]
The sentence "The constraints from visual odometry, lidar odometry, IMU preintegration, and loop closure are optimized jointly in the factor graph" is mentioned in related articles.
but it seems that visual constrains and inertial constrains are not contained in SAM optimization of mapOptimization.cpp file.

**Comment by gaopenggang** [comment]
Interesting question! I guess it is hard to run in real-time if the visual feature residuals also are included in the factor graph. It is possible to consider the output  of the VIS system as one factor, then it is jointly optimized with point-to-line/plane in lidar, IMU preintegration, and loop closure.

**Comment by wjf1997** [comment]
cannot agree with you any more



---- Replied Message ----
| From | GAO ***@***.***> |
| Date | 06/29/2023 18:20 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [TixiaoShan/LVI-SAM] difference between code and article (Issue #57) |

Interesting question! I guess it is hard to run in real-time if the visual feature residuals also are included in the factor graph. It is possible to consider the output of the VIS system as one factor, then it is jointly optimized with point-to-line/plane in lidar, IMU preintegration, and loop closure.

**Comment by shamengjun** [comment]
Actually, the author in code had commented it as picture :
![Selection_022](https://github.com/TixiaoShan/LVI-SAM/assets/26789832/c49ddbef-50de-4a85-befa-45d80100b5e6)
if the lidar odometry is degenerate, then consider add visual odometry constraint, but the benefits are not obvious.
I think vins odometry and lidar odometry output frequency is strictly as the same, so the pose alignment error can cause extra error, so the benefits are not obvious?

**Comment by shamengjun** [comment]
Actually, the code author has commented it as picture shows:
![Selection_022](https://github.com/TixiaoShan/LVI-SAM/assets/26789832/8a2c68e7-f6cc-4a85-9840-b856280f058b)

if the lidar odometry is degenerate, then consider add visual odometry constraint, but the benefits are not obvious.
I think vins odometry and lidar odometry output frequency is strictly not the same, so the pose alignment process can cause extra error, so the benefits are not obvious?
