### ISSUE TITLE
visual feature error

### ISSUE THREAD

**Issue by brian890815** [TixiaoShan/LVI-SAM#68]
I run it with my equipment, and it show error:
[lvi_sam_visual_feature-7] restarting process
process[lvi_sam_visual_feature-7]: started with pid [5038]
[ INFO] [1710754726.644226917]: ----> Visual Feature Tracker Started.
[ WARN] [1710754726.651379767]: =vins-feature_tracker read R_imu_lidar : =====================
1 0 0
0 1 0
0 0 1
[ WARN] [1710754726.651464923]: =vins-feature_tracker read t_lidar_imu : =====================
0, 0, 0
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 140) > this->size() (which is 0)
[lvi_sam_visual_feature-7] process has died [pid 5038, exit code -6, cmd /home/vccl/lvi-sam/devel/lib/lvi_sam/lvi_sam_visual_feature __name:=lvi_sam_visual_feature __log:=/home/vccl/.ros/log/31119c60-e509-11ee-9c47-5c925ed391cc/lvi_sam_visual_feature-7.log].
log file: /home/vccl/.ros/log/31119c60-e509-11ee-9c47-5c925ed391cc/lvi_sam_visual_feature-7*.log

Same equipment can run Vins-mono and lio-sam

**Comment by zs1013** [comment]
> 我用我的设备运行它，它显示错误：[lvi_sam_visual_feature-7] 重新启动进程进程 [lvi_sam_visual_feature-7]：从 PID 启动 [5038][ 信息 ][1710754726.644226917]：----> 视觉特征跟踪器已启动。[ 警告][1710754726.651379767]： =vins-feature_tracker 读取R_imu_lidar：===================== 1 0 0 0 1 0 0 0 1[ 警告][1710754726.651464923]： =vins-feature_tracker 读取t_lidar_imu ： ===================== 0, 0, 0在引发 'std：：out_of_range' 实例后调用 terminatewhat（）： basic_string：：substr： __pos （为 140） > this->size（） （为 0）[lvi_sam_visual_feature-7] 进程已死 [PID 5038，退出代码 -6，cmd /home/vccl/lvi-sam/devel/lib/lvi_sam/lvi_sam_visual_feature __name：=lvi_sam_visual_feature __log：=/home/vccl/.ros/log/31119c60-e509-11ee-9c47-5c925ed391cc/lvi_sam_visual_feature-7.log]。日志文件：/home/vccl/.ros/log/31119c60-e509-11ee-9c47-5c925ed391cc/lvi_sam_visual_feature-7*.log
> 
> 相同的设备可以运行 Vins-mono 和 lio-sam

 i have same issue , how do  you solve it ? thank y.
